"use client";

import { useMemo } from "react";
import {
  AreaChart,
  Area,
  XAxis,
  YAxis,
  Tooltip,
  ResponsiveContainer,
  CartesianGrid,
  TooltipProps,
} from "recharts";
import { REVENUE_COLORS, RevenuePeriodData } from "@/types/revenue";
import { subDays, format } from "date-fns";

interface RevenueAreaChartProps {
  data: number[] | RevenuePeriodData[];
  height?: number;
  stacked?: boolean;
}

// Helper to determine revenue health based on diversification
function getRevenueDiversification(
  yieldShare: number,
  borrowingFees: number
): { label: string; color: string; icon: string } {
  const total = yieldShare + borrowingFees;
  if (total === 0) return { label: "No data", color: "text-gray-500", icon: "⚪" };

  const maxShare = Math.max(yieldShare, borrowingFees) / total;

  if (maxShare <= 0.4) {
    return { label: "Well Diversified", color: "text-emerald-600", icon: "🟢" };
  }
  if (maxShare <= 0.6) {
    return { label: "Moderately Diversified", color: "text-amber-600", icon: "🟡" };
  }
  return { label: "Concentrated", color: "text-red-600", icon: "🔴" };
}

function CustomTooltip({ active, payload, label }: TooltipProps<number, string>) {
  if (!active || !payload || payload.length === 0) {
    return null;
  }

  // Calculate totals and identify dominant source
  const sources = payload.filter((p) => p.dataKey !== "total");
  const isSimple = sources.length === 0;

  if (isSimple) {
    // Simple sparkline data
    const total = payload[0]?.value as number || 0;
    return (
      <div className="bg-white shadow-lg border border-gray-200 rounded-lg p-4 max-w-xs">
        <div className="border-b border-gray-100 pb-2 mb-3">
          <p className="text-sm font-semibold text-gray-900 flex items-center gap-2">
            <span>📅</span> {label}
          </p>
          <p className="text-xs text-gray-500 mt-1">
            Daily revenue generated by the protocol from all sources combined.
          </p>
        </div>
        <div className="flex items-center justify-between gap-4 text-sm">
          <span className="flex items-center gap-2">
            <span
              className="w-3 h-3 rounded-full"
              style={{ backgroundColor: REVENUE_COLORS.total }}
            />
            <span className="text-gray-600">Total Revenue</span>
          </span>
          <span className="font-semibold text-gray-900">
            ${total.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
          </span>
        </div>
      </div>
    );
  }

  // Detailed stacked data with multiple sources
  const yieldShare = payload.find((p) => p.dataKey === "yieldShare")?.value as number || 0;
  const borrowingFees = payload.find((p) => p.dataKey === "borrowingFees")?.value as number || 0;

  const total = yieldShare + borrowingFees;

  // Find dominant source
  const sourceValues = [
    { key: "yieldShare", name: "Yield Share", value: yieldShare, color: REVENUE_COLORS.yieldShare },
    { key: "borrowingFees", name: "Borrowing Fees", value: borrowingFees, color: REVENUE_COLORS.borrowingFees },
  ].filter((s) => s.value > 0);

  const dominant = sourceValues.sort((a, b) => b.value - a.value)[0];
  const dominantPct = total > 0 ? (dominant?.value / total * 100) : 0;

  const diversification = getRevenueDiversification(yieldShare, borrowingFees);

  return (
    <div className="bg-white shadow-lg border border-gray-200 rounded-lg p-4 max-w-xs">
      {/* Header with business context */}
      <div className="border-b border-gray-100 pb-2 mb-3">
        <p className="text-sm font-semibold text-gray-900 flex items-center gap-2">
          <span>📅</span> {label}
        </p>
        <p className="text-xs text-gray-500 mt-1">
          Revenue sources generating yield for the protocol. Higher diversification = more stable revenue.
        </p>
      </div>

      {/* Revenue sources */}
      <div className="space-y-1.5 mb-3">
        {payload.map((entry, index) => (
          <div key={index} className="flex items-center justify-between gap-4 text-sm">
            <span className="flex items-center gap-2">
              <span
                className="w-3 h-3 rounded-full"
                style={{ backgroundColor: entry.color }}
              />
              <span className="text-gray-600">
                {entry.dataKey === "yieldShare"
                  ? "Yield Share"
                  : entry.dataKey === "borrowingFees"
                    ? "Borrowing Fees"
                    : "Total"}
              </span>
            </span>
            <span className="font-medium text-gray-900">
              ${(entry.value as number).toLocaleString(undefined, {
                minimumFractionDigits: 2,
                maximumFractionDigits: 2,
              })}
            </span>
          </div>
        ))}
      </div>

      {/* Derived insights */}
      <div className="border-t border-gray-100 pt-2 space-y-1.5">
        <div className="flex items-center justify-between gap-4 text-sm">
          <span className="text-gray-600 font-medium">Daily Total</span>
          <span className="font-semibold text-gray-900">
            ${total.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
          </span>
        </div>
        {dominant && (
          <div className="flex items-center justify-between gap-4 text-sm">
            <span className="text-gray-600">Dominant Source</span>
            <span className="font-medium text-indigo-600">
              {dominant.name} ({dominantPct.toFixed(0)}%)
            </span>
          </div>
        )}
        <div className="flex items-center justify-between gap-4 text-sm">
          <span className="text-gray-600">Diversification</span>
          <span className={`font-medium ${diversification.color}`}>
            {diversification.label} {diversification.icon}
          </span>
        </div>
      </div>
    </div>
  );
}

export function RevenueAreaChart({
  data,
  height = 300,
  stacked = false,
}: RevenueAreaChartProps) {
  const chartData = useMemo(() => {
    // Handle simple sparkline data (array of numbers)
    if (data.length === 0) return [];

    if (typeof data[0] === "number") {
      const today = new Date();
      return (data as number[]).map((value, index) => ({
        date: format(subDays(today, data.length - 1 - index), "MMM d"),
        total: value,
      }));
    }

    // Handle detailed period data
    return (data as RevenuePeriodData[]).map((item) => ({
      date: item.period,
      yieldShare: item.yieldShare,
      borrowingFees: item.borrowingFees,
      total: item.total,
    }));
  }, [data]);

  if (chartData.length === 0) {
    return (
      <div
        className="flex items-center justify-center text-gray-400"
        style={{ height }}
      >
        No data available
      </div>
    );
  }

  const isSimpleData = typeof data[0] === "number";

  const formatYAxis = (value: number) => {
    if (value >= 1000000) return `$${(value / 1000000).toFixed(1)}M`;
    if (value >= 1000) return `$${(value / 1000).toFixed(0)}K`;
    return `$${value.toFixed(0)}`;
  };

  return (
    <ResponsiveContainer width="100%" height={height}>
      <AreaChart data={chartData} margin={{ top: 10, right: 10, left: 0, bottom: 0 }}>
        <defs>
          <linearGradient id="colorTotal" x1="0" y1="0" x2="0" y2="1">
            <stop offset="5%" stopColor={REVENUE_COLORS.total} stopOpacity={0.3} />
            <stop offset="95%" stopColor={REVENUE_COLORS.total} stopOpacity={0} />
          </linearGradient>
          <linearGradient id="colorYield" x1="0" y1="0" x2="0" y2="1">
            <stop offset="5%" stopColor={REVENUE_COLORS.yieldShare} stopOpacity={0.3} />
            <stop offset="95%" stopColor={REVENUE_COLORS.yieldShare} stopOpacity={0} />
          </linearGradient>
        </defs>
        <CartesianGrid strokeDasharray="3 3" stroke="#f0f0f0" />
        <XAxis
          dataKey="date"
          axisLine={false}
          tickLine={false}
          tick={{ fontSize: 12, fill: "#6b7280" }}
        />
        <YAxis
          tickFormatter={formatYAxis}
          axisLine={false}
          tickLine={false}
          tick={{ fontSize: 12, fill: "#6b7280" }}
        />
        <Tooltip content={<CustomTooltip />} />

        {isSimpleData ? (
          <Area
            type="monotone"
            dataKey="total"
            stroke={REVENUE_COLORS.total}
            strokeWidth={2}
            fillOpacity={1}
            fill="url(#colorTotal)"
          />
        ) : stacked ? (
          <>
            <Area
              type="monotone"
              dataKey="yieldShare"
              stackId="1"
              stroke={REVENUE_COLORS.yieldShare}
              fill="url(#colorYield)"
            />
          </>
        ) : (
          <Area
            type="monotone"
            dataKey="total"
            stroke={REVENUE_COLORS.total}
            strokeWidth={2}
            fillOpacity={1}
            fill="url(#colorTotal)"
          />
        )}
      </AreaChart>
    </ResponsiveContainer>
  );
}

export default RevenueAreaChart;
